<?php defined('BASEPATH') OR exit('No direct script access allowed');

/**
 * Description of Migration_add_mainmenu
 *
 * @author marwansaleh
 */
class Migration_add_mainmenu extends MY_Migration {
    protected $_table_name = 'ref_mainmenu';
    protected $_primary_key = 'id';
    protected $_fields = array(
        'id'    => array (
            'type'  => 'INT',
            'constraint' => 11,
            'unsigned' => TRUE,
            'auto_increment' => TRUE
        ),
        'parent'    => array (
            'type'  => 'INT',
            'constraint' => 11,
            'default' => 0
        ),
        'module'   => array(
            'type'  => 'INT',
            'constraint' => 11,
            'null' => FALSE
        ),
        'caption'   => array(
            'type'  => 'VARCHAR',
            'constraint' => 50,
            'null' => TRUE
        ),
        'title' => array(
            'type'  => 'VARCHAR',
            'constraint' => 254,
            'null' => TRUE
        ),
        'icon'   => array(
            'type'  => 'VARCHAR',
            'constraint' => 50,
            'null' => TRUE
        ),
        'link'   => array(
            'type'  => 'VARCHAR',
            'constraint' => 254,
            'null' => TRUE
        ),
        'sort'   => array(
            'type'  => 'INT',
            'constraint' => 3,
            'default' => 0
        ),
        'hidden'   => array(
            'type'  => 'TINYINT',
            'constraint' => 1,
            'default' => 0
        ),
        'created'   => array(
            'type'  => 'INT',
            'constraint' => 11,
            'unsigned' => TRUE,
            'default' => 0
        ),
        'created_by'   => array(
            'type'  => 'INT',
            'constraint' => 11,
            'unsigned' => TRUE,
            'default' => 0
        ),
        'modified'   => array(
            'type'  => 'INT',
            'constraint' => 11,
            'unsigned' => TRUE,
            'default' => 0
        ),
        'modified_by'   => array(
            'type'  => 'INT',
            'constraint' => 11,
            'unsigned' => TRUE,
            'default' => 0
        )
    );
    
    public function up(){
        parent::up();
        //Need seeding ?
        $this->_seed(array(
            array(
                'id'            => 1,
                'parent'        => 0,
                'module'        => CT_MODULE_DASHBOARD,
                'caption'       => 'Dashboard',
                'title'         => 'Display important parameters',
                'icon'          => 'fa-dashboard',
                'link'          => 'dashboard',
                'sort'          => 0,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 2,
                'parent'        => 0,
                'module'        => CT_MODULE_MARKETING,
                'caption'       => 'Modul Marketing',
                'title'         => 'Mengelola aktifitas produksi',
                'icon'          => 'fa-briefcase',
                'link'          => NULL,
                'sort'          => 1,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 3,
                'parent'        => 2,
                'module'        => CT_MODULE_MARKETING,
                'caption'       => 'Placing Slip',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => NULL,
                'sort'          => 0,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 4,
                'parent'        => 2,
                'module'        => CT_MODULE_MARKETING,
                'caption'       => 'Pengesahan Placing Slip',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => NULL,
                'sort'          => 1,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 5,
                'parent'        => 2,
                'module'        => CT_MODULE_MARKETING,
                'caption'       => 'Polis General',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => NULL,
                'sort'          => 2,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 6,
                'parent'        => 2,
                'module'        => CT_MODULE_MARKETING,
                'caption'       => 'Pengesahan Polis General',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => NULL,
                'sort'          => 3,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 7,
                'parent'        => 2,
                'module'        => CT_MODULE_MARKETING,
                'caption'       => 'Placing Eben',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => NULL,
                'sort'          => 4,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 8,
                'parent'        => 2,
                'module'        => CT_MODULE_MARKETING,
                'caption'       => 'Quotation Eben',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => NULL,
                'sort'          => 5,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 9,
                'parent'        => 2,
                'module'        => CT_MODULE_MARKETING,
                'caption'       => 'Deklarasi Jiwa Kredit',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => NULL,
                'sort'          => 6,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 10,
                'parent'        => 2,
                'module'        => CT_MODULE_MARKETING,
                'caption'       => 'Endorsement',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => NULL,
                'sort'          => 7,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 11,
                'parent'        => 2,
                'module'        => CT_MODULE_MARKETING,
                'caption'       => 'Polis Eben Entry',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => NULL,
                'sort'          => 8,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 12,
                'parent'        => 2,
                'module'        => CT_MODULE_MARKETING,
                'caption'       => 'Pengesahan Polis Eben',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => NULL,
                'sort'          => 9,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 13,
                'parent'        => 2,
                'module'        => CT_MODULE_MARKETING,
                'caption'       => 'Cetak Debit Nota',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => NULL,
                'sort'          => 10,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 14,
                'parent'        => 0,
                'module'        => CT_MODULE_KEUANGAN,
                'caption'       => 'Modul Keuangan',
                'title'         => 'Mengatur neraca dan piutang',
                'icon'          => 'fa-dollar',
                'link'          => NULL,
                'sort'          => 2,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 15,
                'parent'        => 14,
                'module'        => CT_MODULE_KEUANGAN,
                'caption'       => 'Jurnal Kas Masuk',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => NULL,
                'sort'          => 0,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 16,
                'parent'        => 14,
                'module'        => CT_MODULE_KEUANGAN,
                'caption'       => 'Jurnal Kas Keluar',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => NULL,
                'sort'          => 1,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 17,
                'parent'        => 14,
                'module'        => CT_MODULE_KEUANGAN,
                'caption'       => 'Jurnal Bank Masuk',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => NULL,
                'sort'          => 2,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 18,
                'parent'        => 14,
                'module'        => CT_MODULE_KEUANGAN,
                'caption'       => 'Jurnal Bank Masuk (Komisi)',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => NULL,
                'sort'          => 3,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 19,
                'parent'        => 14,
                'module'        => CT_MODULE_KEUANGAN,
                'caption'       => 'Jurnal Bank Keluar',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => NULL,
                'sort'          => 4,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 20,
                'parent'        => 14,
                'module'        => CT_MODULE_KEUANGAN,
                'caption'       => 'Jurnal Umum',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => NULL,
                'sort'          => 5,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 21,
                'parent'        => 14,
                'module'        => CT_MODULE_KEUANGAN,
                'caption'       => 'Jurnal Nota Masuk Cabang',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => NULL,
                'sort'          => 6,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 22,
                'parent'        => 14,
                'module'        => CT_MODULE_KEUANGAN,
                'caption'       => 'Jurnal Auto',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => NULL,
                'sort'          => 7,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 23,
                'parent'        => 14,
                'module'        => CT_MODULE_KEUANGAN,
                'caption'       => 'Penyelesaian Piutang',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => NULL,
                'sort'          => 8,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 24,
                'parent'        => 14,
                'module'        => CT_MODULE_KEUANGAN,
                'caption'       => 'Saldo Awal',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => NULL,
                'sort'          => 9,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 25,
                'parent'        => 0,
                'module'        => CT_MODULE_MASTER,
                'caption'       => 'MASTER DATA',
                'title'         => 'Mengelola data master',
                'icon'          => 'fa-building',
                'link'          => NULL,
                'sort'          => 3,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 26,
                'parent'        => 25,
                'module'        => CT_MODULE_MASTER,
                'caption'       => 'Sumber Bisnis',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => 'master/sumberbisnis',
                'sort'          => 0,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 27,
                'parent'        => 25,
                'module'        => CT_MODULE_MASTER,
                'caption'       => 'Jenis Asuransi',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => 'master/jenisasuransi',
                'sort'          => 1,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 28,
                'parent'        => 25,
                'module'        => CT_MODULE_MASTER,
                'caption'       => 'Asuradur',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => 'master/asuradur',
                'sort'          => 2,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 29,
                'parent'        => 25,
                'module'        => CT_MODULE_MASTER,
                'caption'       => 'Broker',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => 'master/broker',
                'sort'          => 3,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 30,
                'parent'        => 25,
                'module'        => CT_MODULE_MASTER,
                'caption'       => 'Wilayah',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => 'master/wilayah',
                'sort'          => 4,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 31,
                'parent'        => 25,
                'module'        => CT_MODULE_MASTER,
                'caption'       => 'Jenis Usaha',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => 'master/jenisusaha',
                'sort'          => 5,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 32,
                'parent'        => 25,
                'module'        => CT_MODULE_MASTER,
                'caption'       => 'Valuta',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => 'master/valuta',
                'sort'          => 6,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 33,
                'parent'        => 25,
                'module'        => CT_MODULE_MASTER,
                'caption'       => 'Jenis Penyakit',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => 'master/jenispenyakit',
                'sort'          => 7,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 34,
                'parent'        => 25,
                'module'        => CT_MODULE_MASTER,
                'caption'       => 'Rumah Sakit',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => 'master/rumahsakit',
                'sort'          => 8,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 35,
                'parent'        => 25,
                'module'        => CT_MODULE_MASTER,
                'caption'       => 'Salesman',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => 'master/salesman',
                'sort'          => 9,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 36,
                'parent'        => 0,
                'module'        => CT_MODULE_USERMGT,
                'caption'       => 'User Management',
                'title'         => 'Mengelola user, grup dan hak akses',
                'icon'          => 'fa-users',
                'link'          => NULL,
                'sort'          => 4,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 37,
                'parent'        => 36,
                'module'        => CT_MODULE_USERMGT,
                'caption'       => 'Daftar Grup',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => 'usermgt/group',
                'sort'          => 0,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 38,
                'parent'        => 36,
                'module'        => CT_MODULE_USERMGT,
                'caption'       => 'Kelola User',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => 'usermgt/user',
                'sort'          => 1,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 39,
                'parent'        => 36,
                'module'        => CT_MODULE_USERMGT,
                'caption'       => 'User Profile',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => 'usermgt/profile',
                'sort'          => 2,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 40,
                'parent'        => 0,
                'module'        => CT_MODULE_SYSTEM,
                'caption'       => 'System Configuration',
                'title'         => 'Mengatur parameter sistem, backup, etc',
                'icon'          => 'fa-cogs',
                'link'          => NULL,
                'sort'          => 5,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 41,
                'parent'        => 40,
                'module'        => CT_MODULE_SYSTEM,
                'caption'       => 'Environment Variables',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => NULL,
                'sort'          => 0,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 42,
                'parent'        => 40,
                'module'        => CT_MODULE_SYSTEM,
                'caption'       => 'Database',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => NULL,
                'sort'          => 1,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 43,
                'parent'        => 42,
                'module'        => CT_MODULE_SYSTEM,
                'caption'       => 'Backup',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => NULL,
                'sort'          => 0,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 44,
                'parent'        => 42,
                'module'        => CT_MODULE_SYSTEM,
                'caption'       => 'Restore',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => NULL,
                'sort'          => 1,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 45,
                'parent'        => 40,
                'module'        => CT_MODULE_SYSTEM,
                'caption'       => 'Setup Menu',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => 'system/menu/',
                'sort'          => 2,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 46,
                'parent'        => 40,
                'module'        => CT_MODULE_SYSTEM,
                'caption'       => 'System log',
                'title'         => NULL,
                'icon'          => NULL,
                'link'          => 'system/log',
                'sort'          => 3,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 47,
                'parent'        => 0,
                'module'        => CT_MODULE_MANUAL,
                'caption'       => 'MANUAL & GUIDE',
                'title'         => 'Manual penggunaan aplikasi',
                'icon'          => 'fa-book',
                'link'          => NULL,
                'sort'          => 8,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 48,
                'parent'        => 47,
                'module'        => CT_MODULE_MANUAL,
                'caption'       => 'User manual',
                'title'         => 'Manual penggunaan aplikasi (user)',
                'icon'          => NULL,
                'link'          => 'manual/usermanual',
                'sort'          => 0,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 49,
                'parent'        => 47,
                'module'        => CT_MODULE_MANUAL,
                'caption'       => 'Developer manual',
                'title'         => 'Manual aplikasi (developer)',
                'icon'          => NULL,
                'link'          => 'manual/devmanual',
                'sort'          => 1,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 50,
                'parent'        => 0,
                'module'        => CT_MODULE_REPORTING,
                'caption'       => 'Modul Reporting',
                'title'         => 'Laporan produksi dan keuangan',
                'icon'          => 'fa-bar-chart-o',
                'link'          => NULL,
                'sort'          => 8,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 51,
                'parent'        => 50,
                'module'        => CT_MODULE_REPORTING,
                'caption'       => 'Laporan Produksi',
                'title'         => 'Laporan produksi',
                'icon'          => NULL,
                'link'          => 'report/produksi',
                'sort'          => 0,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            ),
            array(
                'id'            => 52,
                'parent'        => 50,
                'module'        => CT_MODULE_REPORTING,
                'caption'       => 'Laporan Keuangan',
                'title'         => 'Laporan keuangan',
                'icon'          => NULL,
                'link'          => 'report/keuangan',
                'sort'          => 1,
                'hidden'        => 0,
                'created'       => time(),
                'created_by'    => 1,
                'modified'      => time(),
                'modified_by'   => 1
            )
        ));
    }
}

/*
 * filename : 014_add_mainmenu.php
 * location : /application/migrations/014_add_mainmenu.php
 */
